-- Local test fixture only: models the legacy schema referenced by application code.
-- This is NOT a production baseline migration or a copy of the live schema.
create role anon nologin;
create role authenticated nologin;
create schema auth;
grant usage on schema auth to anon,authenticated;
create table auth.users (
  id uuid primary key, email text, email_confirmed_at timestamptz,
  raw_user_meta_data jsonb default '{}'
);
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;
$$;
create table public.utilizatori (
  id bigint generated by default as identity primary key,
  nume_complet text, email text, telefon text, nume_firma text, parola text,
  status text, rol text
);
create table public.produse (
  id bigint generated by default as identity primary key,
  cod_bara text unique, nume_produs text, categorie text, brand text,
  varsta_recomandata text, gen text, material text, pret_retail numeric,
  pret_engros numeric, bucati_per_cutie integer, stoc_actual integer default 0,
  stoc_critic integer default 10, imagini text[], descriere text
);
insert into auth.users(id,email,email_confirmed_at) values
('11111111-1111-4111-8111-111111111111','admin@example.invalid',now()),
('22222222-2222-4222-8222-222222222222','customer@example.invalid',now());
insert into public.utilizatori(nume_complet,email,status,rol) values
('Admin','admin@example.invalid','approved','admin'),
('Customer','customer@example.invalid','approved','user');
insert into public.produse(cod_bara,nume_produs,stoc_actual,stoc_critic)
values('legacy-stock','Legacy toy',7,2);
